[package]
name = "solver"
version = "0.1.0"
edition = "2024"

[dependencies]
solver-ir = { path = "solver-ir" }
solver-macros = { path = "solver-macros" }

[workspace]
members = [
    "solver-ir",
    "solver-macros",
]
